spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myBank?&serverTimezone=Asia/Seoul
    username: root
    password: aszx99

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: hello.world.ee.ff